// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *    int32 page_number = 2;
   *    int32 result_per_page = 3;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   *    int32 page_number = 2;
   *    int32 result_per_page = 3;
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
