// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface SearchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
