// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public final class Student {
  private Student() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StuResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StuResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StuResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StuResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StuRequestStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StuRequestStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StuResponseStream_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StuResponseStream_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/resources/proto/Stu.proto\"\033\n\r" +
      "SearchRequest\022\n\n\002id\030\001 \001(\t\"\036\n\016SearchRespo" +
      "nse\022\014\n\004name\030\001 \001(\t\"4\n\013StuResponse\022\n\n\002id\030\001" +
      " \001(\t\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\t\"4\n\017StuRe" +
      "sponseList\022!\n\013stuResponse\030\001 \003(\0132\014.StuRes" +
      "ponse\"\037\n\020StuRequestStream\022\013\n\003req\030\001 \001(\t\"!" +
      "\n\021StuResponseStream\022\014\n\004resp\030\001 \001(\t2\207\002\n\016St" +
      "udentService\022/\n\014QueryStuById\022\016.SearchReq" +
      "uest\032\017.SearchResponse\0229\n\027QueryStuByIdStr" +
      "eam2Resp\022\016.SearchRequest\032\014.StuResponse0\001" +
      "\022=\n\027QueryStuByIdReqByStream\022\016.SearchRequ" +
      "est\032\020.StuResponseList(\001\022J\n\035QueryStuByIdR" +
      "eqAndResp2Stream\022\021.StuRequestStream\032\022.St" +
      "uResponseStream(\0010\001B%\n\030com.zy.grpc.proto" +
      ".serverB\007StudentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchResponse_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_StuResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StuResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StuResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
    internal_static_StuResponseList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_StuResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StuResponseList_descriptor,
        new java.lang.String[] { "StuResponse", });
    internal_static_StuRequestStream_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StuRequestStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StuRequestStream_descriptor,
        new java.lang.String[] { "Req", });
    internal_static_StuResponseStream_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_StuResponseStream_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StuResponseStream_descriptor,
        new java.lang.String[] { "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
