// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface StuRequestStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StuRequestStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string req = 1;</code>
   */
  java.lang.String getReq();
  /**
   * <code>string req = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqBytes();
}
