// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface StuResponseStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StuResponseStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resp = 1;</code>
   */
  java.lang.String getResp();
  /**
   * <code>string resp = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespBytes();
}
