// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface StuResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StuResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string age = 3;</code>
   */
  java.lang.String getAge();
  /**
   * <code>string age = 3;</code>
   */
  com.google.protobuf.ByteString
      getAgeBytes();
}
