// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

/**
 * Protobuf type {@code StuResponseList}
 */
public  final class StuResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StuResponseList)
    StuResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StuResponseList.newBuilder() to construct.
  private StuResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StuResponseList() {
    stuResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StuResponseList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StuResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              stuResponse_ = new java.util.ArrayList<StuResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            stuResponse_.add(
                input.readMessage(StuResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        stuResponse_ = java.util.Collections.unmodifiableList(stuResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Student.internal_static_StuResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Student.internal_static_StuResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StuResponseList.class, StuResponseList.Builder.class);
  }

  public static final int STURESPONSE_FIELD_NUMBER = 1;
  private java.util.List<StuResponse> stuResponse_;
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  public java.util.List<StuResponse> getStuResponseList() {
    return stuResponse_;
  }
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  public java.util.List<? extends StuResponseOrBuilder>
      getStuResponseOrBuilderList() {
    return stuResponse_;
  }
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  public int getStuResponseCount() {
    return stuResponse_.size();
  }
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  public StuResponse getStuResponse(int index) {
    return stuResponse_.get(index);
  }
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  public StuResponseOrBuilder getStuResponseOrBuilder(
      int index) {
    return stuResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stuResponse_.size(); i++) {
      output.writeMessage(1, stuResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < stuResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, stuResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StuResponseList)) {
      return super.equals(obj);
    }
    StuResponseList other = (StuResponseList) obj;

    if (!getStuResponseList()
        .equals(other.getStuResponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStuResponseCount() > 0) {
      hash = (37 * hash) + STURESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getStuResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StuResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StuResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StuResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StuResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StuResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StuResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StuResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StuResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StuResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StuResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StuResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StuResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StuResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StuResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StuResponseList)
          StuResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Student.internal_static_StuResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Student.internal_static_StuResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StuResponseList.class, StuResponseList.Builder.class);
    }

    // Construct using com.zy.grpc.proto.server.bean.StuResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStuResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stuResponseBuilder_ == null) {
        stuResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stuResponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Student.internal_static_StuResponseList_descriptor;
    }

    @java.lang.Override
    public StuResponseList getDefaultInstanceForType() {
      return StuResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public StuResponseList build() {
      StuResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public StuResponseList buildPartial() {
      StuResponseList result = new StuResponseList(this);
      int from_bitField0_ = bitField0_;
      if (stuResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          stuResponse_ = java.util.Collections.unmodifiableList(stuResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stuResponse_ = stuResponse_;
      } else {
        result.stuResponse_ = stuResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StuResponseList) {
        return mergeFrom((StuResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StuResponseList other) {
      if (other == StuResponseList.getDefaultInstance()) return this;
      if (stuResponseBuilder_ == null) {
        if (!other.stuResponse_.isEmpty()) {
          if (stuResponse_.isEmpty()) {
            stuResponse_ = other.stuResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStuResponseIsMutable();
            stuResponse_.addAll(other.stuResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.stuResponse_.isEmpty()) {
          if (stuResponseBuilder_.isEmpty()) {
            stuResponseBuilder_.dispose();
            stuResponseBuilder_ = null;
            stuResponse_ = other.stuResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stuResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStuResponseFieldBuilder() : null;
          } else {
            stuResponseBuilder_.addAllMessages(other.stuResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StuResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StuResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<StuResponse> stuResponse_ =
      java.util.Collections.emptyList();
    private void ensureStuResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        stuResponse_ = new java.util.ArrayList<StuResponse>(stuResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            StuResponse, StuResponse.Builder, StuResponseOrBuilder> stuResponseBuilder_;

    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public java.util.List<StuResponse> getStuResponseList() {
      if (stuResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stuResponse_);
      } else {
        return stuResponseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public int getStuResponseCount() {
      if (stuResponseBuilder_ == null) {
        return stuResponse_.size();
      } else {
        return stuResponseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public StuResponse getStuResponse(int index) {
      if (stuResponseBuilder_ == null) {
        return stuResponse_.get(index);
      } else {
        return stuResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder setStuResponse(
        int index, StuResponse value) {
      if (stuResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStuResponseIsMutable();
        stuResponse_.set(index, value);
        onChanged();
      } else {
        stuResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder setStuResponse(
        int index, StuResponse.Builder builderForValue) {
      if (stuResponseBuilder_ == null) {
        ensureStuResponseIsMutable();
        stuResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        stuResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder addStuResponse(StuResponse value) {
      if (stuResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStuResponseIsMutable();
        stuResponse_.add(value);
        onChanged();
      } else {
        stuResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder addStuResponse(
        int index, StuResponse value) {
      if (stuResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStuResponseIsMutable();
        stuResponse_.add(index, value);
        onChanged();
      } else {
        stuResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder addStuResponse(
        StuResponse.Builder builderForValue) {
      if (stuResponseBuilder_ == null) {
        ensureStuResponseIsMutable();
        stuResponse_.add(builderForValue.build());
        onChanged();
      } else {
        stuResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder addStuResponse(
        int index, StuResponse.Builder builderForValue) {
      if (stuResponseBuilder_ == null) {
        ensureStuResponseIsMutable();
        stuResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        stuResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder addAllStuResponse(
        java.lang.Iterable<? extends StuResponse> values) {
      if (stuResponseBuilder_ == null) {
        ensureStuResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stuResponse_);
        onChanged();
      } else {
        stuResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder clearStuResponse() {
      if (stuResponseBuilder_ == null) {
        stuResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stuResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public Builder removeStuResponse(int index) {
      if (stuResponseBuilder_ == null) {
        ensureStuResponseIsMutable();
        stuResponse_.remove(index);
        onChanged();
      } else {
        stuResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public StuResponse.Builder getStuResponseBuilder(
        int index) {
      return getStuResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public StuResponseOrBuilder getStuResponseOrBuilder(
        int index) {
      if (stuResponseBuilder_ == null) {
        return stuResponse_.get(index);  } else {
        return stuResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public java.util.List<? extends StuResponseOrBuilder>
         getStuResponseOrBuilderList() {
      if (stuResponseBuilder_ != null) {
        return stuResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stuResponse_);
      }
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public StuResponse.Builder addStuResponseBuilder() {
      return getStuResponseFieldBuilder().addBuilder(
          StuResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public StuResponse.Builder addStuResponseBuilder(
        int index) {
      return getStuResponseFieldBuilder().addBuilder(
          index, StuResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .StuResponse stuResponse = 1;</code>
     */
    public java.util.List<StuResponse.Builder>
         getStuResponseBuilderList() {
      return getStuResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            StuResponse, StuResponse.Builder, StuResponseOrBuilder>
        getStuResponseFieldBuilder() {
      if (stuResponseBuilder_ == null) {
        stuResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                StuResponse, StuResponse.Builder, StuResponseOrBuilder>(
                stuResponse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        stuResponse_ = null;
      }
      return stuResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StuResponseList)
  }

  // @@protoc_insertion_point(class_scope:StuResponseList)
  private static final StuResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StuResponseList();
  }

  public static StuResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StuResponseList>
      PARSER = new com.google.protobuf.AbstractParser<StuResponseList>() {
    @java.lang.Override
    public StuResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StuResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StuResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StuResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public StuResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

