// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/Stu.proto

package com.zy.grpc.proto.server.message;

public interface StuResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StuResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  java.util.List<StuResponse>
      getStuResponseList();
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  StuResponse getStuResponse(int index);
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  int getStuResponseCount();
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  java.util.List<? extends StuResponseOrBuilder>
      getStuResponseOrBuilderList();
  /**
   * <code>repeated .StuResponse stuResponse = 1;</code>
   */
  StuResponseOrBuilder getStuResponseOrBuilder(
      int index);
}
